### ISSUE TITLE
Investigate and Repair 'Error: <g> attribute transform: Expected transform function, "null".'

### ISSUE THREAD

**Issue by birm** [sharmalab/Datascope#11]
This error is flooding the console log. It should be fixed or handled.

d3.transform	@	d3.js:806
Error: <g> attribute transform: Expected transform function, "null".

**Comment by birm** [comment]
This happens to pieChart and rowChart but not barChart

**Comment by birm** [comment]
A solution is to modify d3 to accept the case when transform is passed null, adding if (!string) string="translate(0,0)"; to d3.js line 806, just above the error. This, however, does not seem to be the right solution.

**Comment by birm** [comment]
The above fix is in #15, if desired

**Comment by lastlegion** [comment]
Great! Is there a way to fix this outside of the d3.js file. Since for some of our distributions we might be pulling in d3 from CDNs.
