### ISSUE TITLE
More CI Tests

### ISSUE THREAD

**Issue by birm** [sharmalab/Datascope#21]
The fact webpack succeeds isn't alone a good indicator of a good commit/pr. Thus, we should at least unit test some core functionality.

- [x] Fix current tests
- [x] Add more tests

**Comment by lastlegion** [comment]
I agree. We have very few tests right now. https://github.com/sharmalab/Datascope/tree/master/test. But we could include them in the travis builds. And go about adding more tests.

**Comment by birm** [comment]
It looks like the tests are taking more than 15 min (--timeout 999999), so I suspect something is wrong with the tests

**Comment by birm** [comment]
Tests working with #23, proceeding to add more tests

**Comment by birm** [comment]
added some more tests in #26 , will add yet more with new features or with review
