### ISSUE TITLE
scatterPlot example

### ISSUE THREAD

**Issue by birm** [sharmalab/Datascope#28]
As part of at least one of our examples, we should have a bubbleChart.

**Comment by birm** [comment]
getting issues like "d3.js:1526 Error: <path> attribute transform: Expected number, "translate(NaN,NaN)".
attrFunction	@	d3.js:1526
(anonymous)	@	d3.js:1852
d3_selection_each	@	d3.js:1858
d3_selectionPrototype.each	@	d3.js:1851
d3_selectionPrototype.attr	@	d3.js:1508
_chart.plotData	@	dc.js:8782
drawChart	@	dc.js:3594
_chart._doRender	@	dc.js:3570
_chart.render	@	dc.js:1383
dc.renderAll	@	dc.js:176
onFilter	@	bundle.js:135
eventHandler	@	bundle.js:22680
emit	@	bundle.js:22317
trigger	@	bundle.js:22696
(anonymous)	@	bundle.js:22918
(anonymous)	@	d3.js:454
(anonymous)	@	d3.js:438
event	@	d3.js:522
respond	@	d3.js:400"

**Comment by lastlegion** [comment]
I tried the scatter plots and they seem to be working when the attribute does not have any other filters associated with it.

**Comment by birm** [comment]
Okay, it's in examples/visualization_test on the context_vis branch right now.
