### ISSUE TITLE
Implement/Fix bubbleChart

### ISSUE THREAD

**Issue by birm** [sharmalab/Datascope#29]
It looks like bubbleChart may not actually be implemented:

https://github.com/sharmalab/Datascope/blob/3ec120f41c9d182102796dbf2a8e18222aab629d/public/javascripts/src/components/Visualizations/Visualization.jsx

**Comment by lastlegion** [comment]
The code is here: https://github.com/sharmalab/Datascope/blob/master/public/javascripts/src/components/Visualizations/BubbleChart.jsx

We haven't tested the bubble charts in a while so it's possible that some of the changes might have broken this.
