### ISSUE TITLE
Table visualization shows rows as clickable when they are not

### ISSUE THREAD

**Issue by sharmaashish** [sharmalab/Datascope#49]
The table visualization does not support clickable rows. However the icon changes when one is browsing a table. This gives the user an impression that something is broken when they try to click on a row. Please fix asap

**Comment by birm** [comment]
solved with f4274f5

**Comment by sharmaashish** [comment]
Test this, and roll it out on our production systems

**Comment by birm** [comment]
#51 is the pr for this and other features. I could, alternatively, commit the change just to master.

**Comment by birm** [comment]
Hotfix solved with 570861ded7e284213c0e4de0a006a15a9f5d0e20

**Comment by lastlegion** [comment]
This might be more involved, since we want the pointer to be clickable when the table is actually linking out somewhere.

**Comment by sharmaashish** [comment]
Sure, but right now things look like they are clickable, when they are not. And users think that the system is still loading, or it's broken

**Comment by lastlegion** [comment]
Yes hence I've reopened it till we solve both the cases. The hotfix disabled the pointer altogether.
