### ISSUE TITLE
Remove old color scheme

### ISSUE THREAD

**Issue by sharmaashish** [sharmalab/Datascope#5]
On occasion, DataScope reverts to the old color scheme. Or a hybrid of the old and new.

**Comment by birm** [comment]
change from as is without any config to like:

      "primaryColor1": "#f47a7e",
      "primaryColor2": "#ebebeb",
      "headerColor1": "#c9c9d8",
      "headerColor2": "#9c9cab",
      "backgroundColor": "#ebebeb"

**Comment by birm** [comment]
Solved with b2c1dd5
